### ISSUE TITLE
Weird panic during json marshalling

### ISSUE THREAD

**Issue by sosedoff** [figment-networks/near-indexer#1]
Cant reproduce but including for reference: 

```
2020/06/13 10:54:24 started height=7219562 retries=0 lag=1
2020/06/13 10:54:25 started height=7219563 retries=0 lag=0
fatal error: sync: inconsistent mutex state

goroutine 468597 [running]:
runtime.throw(0x173b121, 0x1e)
	/usr/local/Cellar/go/1.14.1/libexec/src/runtime/panic.go:1114 +0x72 fp=0xc000698a08 sp=0xc0006989d8 pc=0x1035ed2
sync.throw(0x173b121, 0x1e)
	/usr/local/Cellar/go/1.14.1/libexec/src/runtime/panic.go:1100 +0x35 fp=0xc000698a28 sp=0xc000698a08 pc=0x1035e55
sync.(*Mutex).lockSlow(0x1cba510)
	/usr/local/Cellar/go/1.14.1/libexec/src/sync/mutex.go:125 +0x1e9 fp=0xc000698a70 sp=0xc000698a28 pc=0x1081499
sync.(*Mutex).Lock(...)
	/usr/local/Cellar/go/1.14.1/libexec/src/sync/mutex.go:81
sync.(*Pool).pinSlow(0x1c8e0e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.14.1/libexec/src/sync/pool.go:213 +0x272 fp=0xc000698af0 sp=0xc000698a70 pc=0x1081f22
sync.(*Pool).pin(0x1c8e0e0, 0xc0001960c0, 0xc0001960c0)
	/usr/local/Cellar/go/1.14.1/libexec/src/sync/pool.go:206 +0x5e fp=0xc000698b18 sp=0xc000698af0 pc=0x1081c7e
sync.(*Pool).Put(0x1c8e0e0, 0x1710e00, 0xc000032200)
	/usr/local/Cellar/go/1.14.1/libexec/src/sync/pool.go:102 +0x3d fp=0xc000698b40 sp=0xc000698b18 pc=0x108187d
encoding/json.Marshal(0x1620960, 0xc00046c100, 0x1cb8818, 0x203000, 0x203000, 0x203000, 0x7411888)
	/usr/local/Cellar/go/1.14.1/libexec/src/encoding/json/encode.go:167 +0xeb fp=0xc000698bb8 sp=0xc000698b40 pc=0x110bccb
github.com/gorilla/rpc/v2/json2.EncodeClientRequest(0x1727a92, 0x5, 0x166e900, 0xc000110870, 0x120, 0x110, 0x16bf080, 0x1, 0x1000000000030)
	/Users/sosedoff/go/pkg/mod/github.com/gorilla/rpc@v1.2.0/v2/json2/client.go:49 +0xc2 fp=0xc000698c08 sp=0xc000698bb8 pc=0x15d6eb2
github.com/figment-networks/near-indexer/near.Client.Call(0xc00034bce0, 0x1a, 0xc000110ff0, 0x0, 0x1727a92, 0x5, 0x166e900, 0xc000110870, 0x161f1e0, 0xc00000c5a0, ...)
	/Users/sosedoff/go/src/github.com/figment-networks/near-indexer/near/client.go:91 +0x85 fp=0xc000698d28 sp=0xc000698c08 pc=0x15d7975
github.com/figment-networks/near-indexer/near.Client.BlockByHeight(...)
	/Users/sosedoff/go/src/github.com/figment-networks/near-indexer/near/client.go:146
github.com/figment-networks/near-indexer/pipeline/sync.fetchBlockData(0xc000520ea0, 0xc0000fe000)
	/Users/sosedoff/go/src/github.com/figment-networks/near-indexer/pipeline/sync/fetch_chain_data.go:18 +0x1da fp=0xc000698fd0 sp=0xc000698d28 pc=0x15dd27a
runtime.goexit()
	/usr/local/Cellar/go/1.14.1/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000698fd8 sp=0xc000698fd0 pc=0x1068691
created by github.com/figment-networks/near-indexer/pipeline/sync.FetchChainData
	/Users/sosedoff/go/src/github.com/figment-networks/near-indexer/pipeline/sync/fetch_chain_data.go:9 +0x79
```

**Comment by sosedoff** [comment]
no longer the case
